steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app-name', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-app-name']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'your-app-name'
    - '--image'
    - 'gcr.io/$PROJECT_ID/your-app-name'
    - '--region'
    - 'your-region'
    - '--platform'
    - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/your-app-name' 